# Generated by Django 4.0.4 on 2022-05-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_core_level_boost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boost',
            name='price',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='core',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
