# Generated by Django 4.0.4 on 2022-06-08 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_boost_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boost',
            name='price',
            field=models.IntegerField(default=10),
        ),
    ]
